name: Deploy Flask App with Terraform + Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve

      - name: Extract EC2 IP from terraform output
        id: ec2ip
        working-directory: ./infra
        run: |
          echo "ip=$(terraform output -raw ec2_public_ip)" >> "$GITHUB_OUTPUT"

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Create Ansible Inventory File
        run: |
          echo "[ec2]" > ansible/inventory.ini
          echo "${{ steps.ec2ip.outputs.ip }} ansible_user=${{ secrets.EC2_SSH_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini

      - name: Add SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/site.yml
